development:
  adapter: postgresql
  database: cable_development
  username: <%= ENV['DATABASE_USER'] %>    # Usando a mesma variável de ambiente do database.yml
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Usando a mesma variável de ambiente do database.yml
  host: localhost

test:
  adapter: postgresql
  database: cable_test
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  database: <%= ENV['CABLE_DATABASE_NAME'] || 'workoutday_production_cable' %>  # Banco de dados para o ActionCable
  username: <%= ENV['DATABASE_USER'] %>    # Usando a mesma variável de ambiente do database.yml
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Usando a mesma variável de ambiente do database.yml
  host: <%= ENV['DATABASE_HOST'] %>  # Usando a variável de ambiente para o host
