# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workoutday_development
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL
  port: 5432
  username: postgres  # Caso o usuário seja o padrão do PostgreSQL
  password: password  # Se você tiver configurado uma senha para o PostgreSQL

test:
  <<: *default
  database: workoutday_test
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL
  port: 5432
  username: postgres  # Caso o usuário seja o padrão do PostgreSQL
  password: password

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  pool: 5
  timeout: 5000
  sslmode: require # Isso garante que a conexão seja feita via SSL

  cache:
    <<: *default
    database: workoutday_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: workoutday_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: workoutday_production_cable
    migrations_paths: db/cable_migrate