default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workoutday_development
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL, se necessário
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: workoutday_test
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL
  port: 5432
  username: postgres
  password: password

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || workoutday_production %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>  # Pode ser uma variável de ambiente
  pool: 5
  timeout: 5000
  sslmode: require

queue:
  <<: *default
  url: <%= ENV['QUEUE_DATABASE_URL'] %>