default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workoutday_development
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL, se necessário
  port: 5432
  username: postgres  # Caso o usuário seja o padrão do PostgreSQL
  password: password  # Se você tiver configurado uma senha para o PostgreSQL

test:
  <<: *default
  database: workoutday_test
  host: 172.17.0.2  # Substitua pelo nome do seu container PostgreSQL
  port: 5432
  username: postgres  # Caso o usuário seja o padrão do PostgreSQL
  password: password

production:
  <<: *default
  # Aqui usamos a DATABASE_URL fornecida pelo Render para simplificar a configuração
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
  sslmode: require # Garantir que a conexão seja feita via SSL